chruby-exec uses .ruby-version if no RUBY spec'd
If chruby-exec is called with a command but no RUBY specified (before
the "--" delimiter), it will attempt to locate a .ruby-version file
in the current working directory or its ancestors (just as chruby_auto
does).

diff --git a/bin/chruby-exec b/bin/chruby-exec
--- a/bin/chruby-exec
+++ b/bin/chruby-exec
@@ -2,9 +2,27 @@
 
 CHRUBY_VERSION="0.3.4"
 
+function chruby_version_from_file() {
+	local dir="$PWD"
+	local version_file
+
+	until [[ -z "$dir" ]]; do
+		version_file="$dir/.ruby-version"
+
+		if [[ -f "$version_file" ]]; then
+			echo $(cat "$version_file")
+			return
+		fi
+
+		dir="${dir%/*}"
+	done
+}
+
 case "$1" in
 	-h|--help)
 		echo "usage: chruby-exec RUBY [RUBYOPTS] -- COMMAND"
+		echo "   or: chruby-exec -- COMMAND"
+		echo "  (in second form, will attempt to use .ruby-version file)"
 		exit
 		;;
 	-v|--version)
@@ -27,6 +45,13 @@ for arg in $@; do
 	else                          argv+=($arg)
 	fi
 done
+
+[[ ! "$argv" ]] && argv=$(chruby_version_from_file)
+
+if [[ ! $argv ]]; then
+	echo "chruby-exec: RUBY (or .ruby-version file) required" >&2
+	exit 1
+fi
 
 if [[ $# -eq 0 ]]; then
 	echo "chruby-exec: COMMAND required" >&2
